import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const base='.production/categories-20261010-215252';
const d=JSON.parse(fs.readFileSync(`${base}/delivery-candidate.json`,'utf8'));
const previous=JSON.parse(fs.readFileSync(`${base}/before/renders/delivery.json`,'utf8'));
if(!JSON.parse(fs.readFileSync(`${base}/check-final.json`,'utf8')).ok)throw Error('Composition gate failed');
const auditPath=`${base}/audio/${path.basename(d.master,'.mp4')}-aac-audit.json`;
const audio=JSON.parse(fs.readFileSync(auditPath,'utf8'));
if(!audio.passed)throw Error('AAC audit failed');
const visual=JSON.parse(fs.readFileSync(`${base}/exported-visual-review.json`,'utf8'));
if(!visual.passed)throw Error('Exported visual review pending or failed');
for(const f of ['master','web'])if(createHash('sha256').update(fs.readFileSync(previous[f])).digest('hex')!==previous.files[f].sha256)throw Error('Historical file changed');
function audioHash(file){const r=spawnSync('/home/xzy/miniconda3/envs/xvla-stable/bin/ffmpeg',['-v','error','-i',file,'-map','0:a:0','-c:a','copy','-f','adts','-'],{maxBuffer:32*1024*1024});if(r.status!==0)throw Error('Audio demux failed');return createHash('sha256').update(r.stdout).digest('hex');}
const aac={master:audioHash(d.master),web:audioHash(d.web)};if(aac.master!==aac.web)throw Error('Web AAC changed');
const stamp=d.id.replace('mind2act-world-promo-','');
d.local_preview=`renders/preview-${stamp}.html`;
const oldHtml=fs.readFileSync(previous.local_preview,'utf8');
fs.writeFileSync(d.local_preview,oldHtml.replaceAll(previous.id.replace('mind2act-world-promo-',''),stamp));
d.contact_sheet=`renders/mind2act-world-contact-${stamp}.jpg`;
fs.copyFileSync(`${base}/rendered/delivery-contact.jpg`,d.contact_sheet);
d.checks.aac=auditPath;
d.checks.web_aac_identical=true;
d.checks.aac_hashes=aac;
d.checks.review=`${base}/QA.md`;
d.checks.exported_frames=`${base}/rendered`;
d.checks.exported_visual=`${base}/exported-visual-review.json`;
d.checks.narrative=`${base}/audio/final-narrative-audit.json`;
d.checks.animation=`${base}/animation-review.json`;
d.source_hashes={};
for(const file of ['index.html',...fs.readdirSync('compositions').filter(n=>n.endsWith('.html')).map(n=>`compositions/${n}`)])d.source_hashes[file]=createHash('sha256').update(fs.readFileSync(file)).digest('hex');
d.verified_at=new Date().toISOString();
d.narrative='Question and three distinct categories → representative Mind/Act/Mind2Act cases → bidirectional coordination, exact logo synthesis and equal three-logo triangle →15 real task videos in3 categories →F Easy/Medium/Hard video comparison →45task-difficulty configurations →collective moonshot invitation.';
d.audio_verification='Independent music/VO stems, statistics VO zero, loudness/correlation/ASR/VAD on final audio. No manual listening certification.';
const json=JSON.stringify(d,null,2)+'\n';
fs.writeFileSync(`renders/delivery-${stamp}.json`,json);fs.writeFileSync('renders/delivery.json',json);fs.writeFileSync(`${base}/delivery-final.json`,json);
fs.copyFileSync('renders/README.md',`${base}/before/renders/README.md`);
fs.writeFileSync('renders/README.md',`# Mind2Act World promotional film\n\nLatest delivery: **${d.files.master.duration.toFixed(2)} seconds,1920×1080,30fps,H.264/AAC**. Authored timeline74.074074s; output rounded to the next video frame.\n\n- Master: ${d.master} (${(d.files.master.bytes/1e6).toFixed(1)}MB).\n- Compact website copy: ${d.web} (${(d.files.web.bytes/1e6).toFixed(1)}MB). AAC is copied without re-encoding.\n- Local player: ${d.local_preview}.\n- Poster: ${d.poster}.\n- Contact sheet: ${d.contact_sheet}.\n- English subtitles: ${d.subtitles.join(', ')}.\n- Editable preview: ${d.preview_url}.\n\nThe three cases illustrate distinct benchmark categories: memory-driven decisions, physically valid execution, and coordinated complete-task requirements. The summary uses two-way paths and exact independent marks plus three dots, resolves the complete logo, then holds all three category marks in a balanced triangle. Real task excerpts become a fifteen-task taxonomy wall. F's three levels use real1× source footage and visible track/grid differences; oversized type leads into a three-row comparison and45configuration payoff.\n\nThe selected blue-cup mealpacking, Act target/trace window and piano observed-sequence EXCERPT window remain. Original wordmark pixels/colors are retained with only the colon excluded from the display window. No piano cover-opening,rhythm-matching,model-state,recovery or performance claim. Sources and definitions are pinned to the user's project archive and reference-insight, not later changing upstream task docs.\n\nFinal checks: composition gate passed; actual MP4 frames and motion contact sheets reviewed; full decode passed for both videos; AAC${audio.loudness_lufs.toFixed(2)}LUFS /${audio.true_peak_dbtp.toFixed(2)}dBTP; Easy/Medium/Hard VO level spread0.05LU; statistics intervals zero narration. Automated ASR/VAD and decoded audio comparisons do not constitute manual listening.\n\nProduction record: ${base}/. Nine sub-compositions, HyperFrames0.8.143 pinned via bash scripts/hyperframes.sh. Historical outputs are retained unchanged; earlier generator scripts are historical and should not be rerun over current compositions.\n`);
const manifest=JSON.parse(fs.readFileSync(`${base}/manifest.json`,'utf8'));
manifest.status='complete';manifest.delivery=d.master;manifest.web=d.web;manifest.duration=d.files.master.duration;manifest.verified_at=d.verified_at;
manifest.history_note='Root begin5b35b2da; delegated logo worker accidentally began7e008e2b before edits; all work belongs to the same user-authorized revision. Source before-backups and source hashes preserve the full changeset.';
fs.writeFileSync(`${base}/manifest.json`,JSON.stringify(manifest,null,2));
console.log(JSON.stringify({id:d.id,master:d.master,web:d.web,preview:d.local_preview,duration:d.files.master.duration}));
