import fs from 'node:fs';
import {createHash} from 'node:crypto';
const base='.production/coordination-20261010-174012';
const delivery=JSON.parse(fs.readFileSync(`${base}/delivery-candidate.json`,'utf8'));
const audit=`${base}/audio/mind2act-world-promo-1080p-20261010-180033-aac-audit.json`;
if(!JSON.parse(fs.readFileSync(audit,'utf8')).passed)throw Error('AAC gate failed');
if(!JSON.parse(fs.readFileSync(`${base}/check-final.json`,'utf8')).ok)throw Error('Composition gate failed');
const previous=JSON.parse(fs.readFileSync(`${base}/before/renders/delivery.json`,'utf8'));
const originalHash=createHash('sha256').update(fs.readFileSync(previous.master)).digest('hex');
if(originalHash!=='44f4584d2fb282b5ac0b3ef6b17c8f3a7001b9ca591da33f3dff3016d9bac413')throw Error('Historical master changed');
const oldMetadata='renders/delivery-20261010-163109.json';
if(!fs.existsSync(oldMetadata))fs.copyFileSync(`${base}/before/renders/delivery.json`,oldMetadata);
delivery.local_preview='renders/preview-20261010-180033.html';
delivery.checks.aac=audit;
delivery.checks.review=`${base}/QA.md`;
delivery.checks.exported_frames=`${base}/rendered`;
delivery.checks.historical_master_sha256=originalHash;
delivery.source_hashes={};
for(const file of ['index.html',...fs.readdirSync('compositions').filter(n=>n.endsWith('.html')).map(n=>`compositions/${n}`)])delivery.source_hashes[file]=createHash('sha256').update(fs.readFileSync(file)).digest('hex');
delivery.verified_at=new Date().toISOString();
const json=JSON.stringify(delivery,null,2)+'\n';
fs.writeFileSync('renders/delivery-20261010-180033.json',json);
fs.writeFileSync('renders/delivery.json',json);
fs.writeFileSync(`${base}/delivery-final.json`,json);
console.log(JSON.stringify({id:delivery.id,master:delivery.master,web:delivery.web,seconds:delivery.files.master.duration,review:delivery.checks.review,previous_master_unchanged:true}));
