"""Astra–Jev proposal content. All new integration claims are explicitly unmeasured."""
MODEL_NAME = "Mind2Act Harness"
MODEL_SUBTITLE = "Contract-Guided Coordination of Cognitive and Reactive Agents for Robotic Manipulation"
COMMIT = "6d3c53eab6adcdfc7b7c4fdda7c9dba5d4fcce41"
REPO = "https://github.com/MuQY1818/mem-planner-harness"
MODULES = [{'id': 'cognitive', 'name': 'GPT-6 Astra · Task Planner', 'label': '任务拆解与升级处理', 'state': '方案设计 · 待实现与验证', 'inputs': '任务指令、可见图像、精确任务账本和异常事件', 'outputs': '子目标契约、感知计划与任务记忆', 'body': '在子目标边界或冲突时组织复杂推理，调用 perception tools 并声明当前执行目标。', 'boundary': '实际 API 标识与调用配置待固定；不把每帧大模型调用当作默认循环。'}, {'id': 'tools', 'name': 'Perception Tools', 'label': '带来源的场景证据', 'state': '方案设计 · 待实现与验证', 'inputs': '允许访问的 RGB / 本体信息与观察目标', 'outputs': 'SceneState：对象、属性、时效、单位和坐标系', 'body': '将感知结果转为结构化事实；任务改变或几何过期时按需刷新。', 'boundary': '预测不是真值；未知坐标变换禁止绑定运动目标。'}, {'id': 'compiler', 'name': 'Evidence-Grounded State Compiler', 'label': '可审计的交接', 'state': '方案设计 · 待实现与验证', 'inputs': '契约、SceneState、回执、记忆与候选引用', 'outputs': '紧凑 DecisionPacket', 'body': '显式组织来源、未知项和当前决策需要的条件。计数、版本和预算比较留在代码中。', 'boundary': '新模块待实现；压缩不得无声丢失关键任务信息。'}, {'id': 'registry', 'name': 'Candidate Registry', 'label': '完整候选绑定', 'state': '方案设计 · 待实现与验证', 'inputs': '授权工具、技能模板、感知结果与允许的变换', 'outputs': '不可变 ID → 完整动作 / 工具请求', 'body': '将连续参数、坐标来源、有效期和检查点绑定为一个候选，不交给独立问题随意拼接。', 'boundary': '协议合法不证明物理可行；候选覆盖与生成成本需要单独测量。'}, {'id': 'reactive', 'name': 'Jev · Candidate Selector', 'label': '局部离散决策', 'state': '方案设计 · 待实现与验证', 'inputs': '文本 DecisionPacket 与预定义候选 criteria', 'outputs': '候选 ID 或拒答 / 升级选项', 'body': '在有效结构化状态上选择完整候选；不直接处理图像或生成任意连续参数。', 'boundary': '版本与限制部署前复核；confidence 不等于物理成功概率。'}, {'id': 'runtime', 'name': 'Guarded Execution Runtime', 'label': '唯一物理执行入口', 'state': '方案设计 · 待实现与验证', 'inputs': '候选 ID、注册表、当前授权和新事件', 'outputs': '动作派发、回执、停止或拒绝', 'body': 'Jev 返回后再次检查版本、时效与预算；健康动作由执行循环延续。', 'boundary': '已有 Runtime 可复用，Jev 适配待实现；独立环境评分器确认最终成功。'}, {'id': 'memory', 'name': 'Bounded Working Memory', 'label': '局内历史而非 RSI', 'state': '方案设计 · 待实现与验证', 'inputs': '任务事实、近期事件、带证据摘要与当前场景', 'outputs': '预算内的相关上下文', 'body': '保留未完成依赖，裁剪无关历史；将稳定任务事实与易过期几何分开管理。', 'boundary': '自由摘要由 Astra 或声明的模块生成；不涉及跨局经验晋升。'}, {'id': 'router', 'name': 'Cost-Aware Router', 'label': '选择何时调用谁', 'state': '方案设计 · 待实现与验证', 'inputs': '时效、候选覆盖、事件、剩余预算与开发阈值', 'outputs': '继续 / 刷新 / Jev / Astra / 停止', 'body': '在任务质量和时限约束下减少冗余调用，记录所有路径的实际总成本。', 'boundary': '路由策略待验证；必要证据不足时不能为省钱绕过检查。'}]
SOURCES = [
 {"id":"state","title":"TypeSafe · State","url":"https://docs.typesafe.ai/concepts/state","description":"文本状态与每请求上下文；图片不是 Jev 输入。"},
 {"id":"choice","title":"TypeSafe · Choice","url":"https://docs.typesafe.ai/primitives/choice","description":"从声明的候选中选择；不代替连续动作参数生成。"},
 {"id":"models","title":"TypeSafe · Models","url":"https://docs.typesafe.ai/models","description":"运行前复核版本、限制与计费；本提案不预设实时性或价格优势。"},
 {"id":"confidence","title":"TypeSafe · Confidence","url":"https://docs.typesafe.ai/confidence","description":"阈值需开发集验证；不把置信度当作物理成功证据。"},
 {"id":"baseline","title":"EvoMemHarness · 参考实现快照","url":REPO+"/tree/"+COMMIT,"description":"已有授权、Runtime 与 notes 的基础，不代表新 Astra–Jev 组合已实现。"},
 {"id":"style","title":"RoboICL · 叙事与图文参考","url":"https://mosi-ai.github.io/RoboICL-GPT6-Astra.github.io/","description":"仅参考页面组织形式；不沿用其算法主张或实验结果。"}
]
