"""Method proposal with separately scoped historical Case7 prototype evidence."""
MODEL_NAME = 'Mind2Act Harness'
MODEL_SUBTITLE = 'Contract-Guided Coordination of Cognitive and Reactive Agents for Robotic Manipulation'
COMMIT = '6d3c53eab6adcdfc7b7c4fdda7c9dba5d4fcce41'
REPO = 'https://github.com/MuQY1818/mem-planner-harness'
MODULES = [{'id': 'cognitive',
  'name': 'GPT-6 Astra · Task Planner',
  'label': '可复用的视觉理解与短期意图',
  'state': 'Case7 外部原型已接通 · 跨任务待验证',
  'inputs': '任务、合法图像／本体状态、实际回执与待处理事件',
  'outputs': '可见事实、未知项、短期意图与授权修订',
  'body': '形成可复用的任务依据，按生命周期、固定事件或 Jev 升级请求更新；当前仍保留巡检和放置后更新。',
  'boundary': '按需减少认知介入是待测目标；不代写 Jev 的动作记忆。'},
 {'id': 'tools',
  'name': 'Visual Perception & Execution Tools',
  'label': '局部证据与连续控制',
  'state': 'Case7 外部原型已接通 · 工具覆盖有限',
  'inputs': '当前授权目标与环境允许的观察',
  'outputs': '区域报告、操作几何、实际执行回执与不确定性',
  'body': '按请求更新局部证据；完成有限抓取或放置的连续控制，不逐运动阶段请求模型。',
  'boundary': '历史 Case7 使用授权 RGB-D；RoboDojo 仅 RGB／本体及主动请求的 RGB 推断工具。'},
 {'id': 'compiler',
  'name': 'Evidence-Grounded State Compiler',
  'label': '可审计的交接',
  'state': 'Case7 编码已有验证 · 选择质量影响待测',
  'inputs': '契约、SceneState、回执、记忆与候选引用',
  'outputs': '紧凑 DecisionPacket',
  'body': '当前意图与最新区域卡片直接提供；旧报告、完整轮廓和诊断按需读取，保留来源与未知项。',
  'boundary': '详情遵守访问窗口；精简字节数不等于节省费用或改善任务表现。'},
 {'id': 'registry',
  'name': 'Candidate Registry',
  'label': '完整候选绑定',
  'state': 'Case7 工具绑定已实现 · 通用注册表待验证',
  'inputs': '授权工具、技能模板、感知结果与允许的变换',
  'outputs': '不可变 ID → 工具＋完整输入绑定',
  'body': '按接口、授权和可用输入生成候选；普通动作一次选择，详情查询单独分级。昂贵计算在工具被选中后启动。',
  'boundary': '候选覆盖限制模型能力；几何失败门控等额外干预必须在对照中披露。'},
 {'id': 'reactive',
  'name': 'Jev · Candidate Selector',
  'label': '动作、信息获取与升级选择',
  'state': 'Case7 外部原型已接通 · 对照收益待测',
  'inputs': '文本 DecisionPacket 与预定义候选 criteria',
  'outputs': '已绑定工具请求、补观察、详情／记忆操作或升级',
  'body': '结合当前报告和新回执决定继续执行、补信息或请求重规划；只在有新事件时选择。',
  'boundary': '不直接看 RGB，不生成任意控制；相比 Astra 或规则是否更划算仍需验证。'},
 {'id': 'runtime',
  'name': 'Guarded Execution Runtime',
  'label': '唯一物理执行入口',
  'state': 'Case7 生命周期已运行 · 跨任务适配待验证',
  'inputs': '候选 ID、注册表、当前授权和新事件',
  'outputs': '动作派发、回执、停止或拒绝',
  'body': '保留在途事件，合并唤醒；派发前检查授权与动作所有权，撤销后等待物理取消确认。',
  'boundary': '不以终局评分指导在线恢复；语义判断属于 Agent，执行协议由 Runtime 管理。'},
 {'id': 'memory',
  'name': 'Bounded Working Memory',
  'label': 'Jev 主动管理的局内动作记录',
  'state': '接口已实现 · 当前开发局未使用',
  'inputs': 'Jev 当前可访问的动作回执与当时可见依据',
  'outputs': '固定字段 ActionMemory、索引及显式读取正文',
  'body': 'Jev 选择保存、读取或删除；程序记录来源、参数、进度、终态与错误，最多 32 条／32 KiB。',
  'boundary': '不自动摘要或写入；最近四次交互与 Cognitive 持久会话分开维护。'},
 {'id': 'router',
  'name': 'Feedback-Driven Cognitive Updates',
  'label': '按反馈分配认知更新',
  'state': '混合触发已运行 · 按需调度收益待测',
  'inputs': '执行事件、最新证据、授权、Jev 请求与预算',
  'outputs': '等待事件／局部决策／请求 Cognitive／终止',
  'body': '研究可复用的目标与易变化的执行证据如何分工；固定现有混合触发，单独比较按需更新。',
  'boundary': '目标是成功能力、成本和完成时间的取舍，不预设调用更少必然更快。'}]
SOURCES = [{'id': 'state',
  'title': 'TypeSafe · State',
  'url': 'https://docs.typesafe.ai/concepts/state',
  'description': '文本状态与每请求上下文；图片不是 Jev 输入。'},
 {'id': 'choice',
  'title': 'TypeSafe · Choice',
  'url': 'https://docs.typesafe.ai/primitives/choice',
  'description': '从声明的候选中选择；不代替连续动作参数生成。'},
 {'id': 'models',
  'title': 'TypeSafe · Models',
  'url': 'https://docs.typesafe.ai/models',
  'description': '运行前复核版本、限制与计费；本提案不预设实时性或价格优势。'},
 {'id': 'confidence',
  'title': 'TypeSafe · Confidence',
  'url': 'https://docs.typesafe.ai/confidence',
  'description': '阈值需开发集验证；不把置信度当作物理成功证据。'},
 {'id': 'baseline',
  'title': 'EvoMemHarness · 参考实现快照',
  'url': 'https://github.com/MuQY1818/mem-planner-harness/tree/6d3c53eab6adcdfc7b7c4fdda7c9dba5d4fcce41',
  'description': '授权、会话与执行生命周期的工程基础；当前 Case7 原型在独立工作区。'},
 {'id': 'style',
  'title': 'RoboICL · 叙事与图文参考',
  'url': 'https://mosi-ai.github.io/RoboICL-GPT6-Astra.github.io/',
  'description': '仅参考页面组织形式；不沿用其算法主张或实验结果。'},
 {'id': 'case7',
  'title': 'Case7 · 历史开发证据',
  'url': 'data/research/case7_development_evidence_20260924.json',
  'description': '同一 seed034 的开发计数、离线评分摘要和来源哈希；不是 World 正式成绩或比较优势。'}]
