(()=>{
const chart=document.querySelector('.moon-chart'),layer=document.querySelector('#nodes'),tip=document.querySelector('.lunar-tooltip'),data=JSON.parse(document.querySelector('#lunar-data').textContent),ns='http://www.w3.org/2000/svg',reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
let mode='A',selected=null,nodes=[],frame=0;
const E=(tag,attrs={},txt)=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(txt!==undefined)n.textContent=txt;return n};
function icon(model,size){const s=E('svg',{x:-size/2,y:-size/2,width:size,height:size,viewBox:'0 0 24 24',class:'brand','aria-hidden':'true'});const doc=new DOMParser().parseFromString(model.icon_svg,'image/svg+xml');for(const c of [...doc.documentElement.children])if(c.tagName!=='title')s.append(document.importNode(c,true));return s}
const avg=m=>(m.mind+m.act+m.coupling)/3;
function attach(g,model,track,rank,score){const floating=E('g',{class:'float-body'});while(g.firstChild)floating.append(g.firstChild);g.append(floating);floating.style.setProperty('--float-duration',(5+rank%4)+'s');floating.style.setProperty('--float-delay',(-rank*.73)+'s');g.setAttribute('class','node');g.setAttribute('role','button');g.setAttribute('tabindex','0');g.dataset.model=model.id;g.setAttribute('aria-label',`${model.name}, ${track}, ${score.toFixed(1)} out of 100`);function show(){tip.replaceChildren();tip.append(Ehtml('b',model.name),Ehtml('span',`${track} · Rank ${rank+1}`),Ehtml('span',`Score ${score.toFixed(1)}/100`),Ehtml('span',`Average ${avg(model).toFixed(1)}/100`));if(mode==='C')tip.append(Ehtml('span',`Mind ${model.mind} · Coupling ${model.coupling} · Act ${model.act}`));tip.hidden=false;const box=chart.getBoundingClientRect(),r=g.getBoundingClientRect();tip.style.left=Math.max(12,Math.min(box.width-230,r.x-box.x-85))+'px';tip.style.top=Math.max(12,r.y-box.y-125)+'px'}g.addEventListener('pointerenter',show);g.addEventListener('pointerleave',()=>tip.hidden=true);g.addEventListener('focus',show);g.addEventListener('blur',()=>tip.hidden=true);g.addEventListener('click',()=>{select(model.id);show()});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(model.id);show()}})}
function Ehtml(tag,txt){const e=document.createElement(tag);e.textContent=txt;return e}
function trackpoint(track,score){const p=document.querySelector('#path-'+track),len=p.getTotalLength(),goal=1030-(1030-320)*Math.max(0,(score-25)/75);let lo=0,hi=len;for(let i=0;i<24;i++){const m=(lo+hi)/2;if(p.getPointAtLength(m).y>goal)lo=m;else hi=m}return p.getPointAtLength((lo+hi)/2)}
function render(next){mode=next;chart.setAttribute('viewBox','0 0 1400 460');document.querySelector('#floating-earth').setAttribute('transform',mode==='B'?'translate(0 500)':'translate(0 180)');document.querySelector('#score-spaces').style.display='none';cancelAnimationFrame(frame);tip.hidden=true;layer.replaceChildren();nodes=[];document.querySelector('#routes').style.display=mode==='A'?'':'none';document.querySelector('#floating-earth').style.display='none';document.querySelector('#side-orbits').style.display='none';document.querySelector('.lunar-world-titles').style.display=mode==='C'?'none':'';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
if(mode!=='C')for(const track of ['mind','coupling','act']){const ranked=[...data.models].sort((a,b)=>b[track]-a[track]);let previousY=-Infinity;ranked.forEach((model,rank)=>{const score=model[track],g=E('g');g.dataset.track=track;let displayScore=score;if(mode==='A'){const natural=1030-(score-25)/75*710;const y=Math.max(natural,previousY+32);previousY=y;displayScore=25+(1030-y)/710*75;}if(mode==='B'&&track==='coupling'){g.append(E('path',{d:'M0 -26 Q23 -10 21 15 L13 25 H-13 L-21 15 Q-23 -10 0 -26Z',class:'capsule'}),E('path',{d:'M-8 25 Q0 48 8 25',class:'flame'}));g.append(icon(model,22))}else{const radius=mode==='A'?14:20;g.append(E('circle',{r:radius,class:'disc'}),icon(model,mode==='A'?20:28))}attach(g,model,{mind:'Mind World',act:'Act World',coupling:'Mind2Act'}[track],rank,score);layer.append(g);nodes.push({g,model,track,rank,score,displayScore,x:{mind:350,coupling:700,act:1050}[track]+{mind:[-52,34,-9,65,-68,13,60,-30,72,-55,5],coupling:[15,-60,54,-15,72,-47,27,-73,8,63,-30],act:[49,-28,7,-68,65,-4,37,-51,70,-17,-63]}[track][rank%11]})})}
else{const ranked=[...data.models].sort((a,b)=>avg(b)-avg(a));ranked.forEach((model,rank)=>{const g=E('g'),x=700+(rank===0?0:(rank%2?-1:1)*Math.ceil(rank/2)*105);g.append(E('path',{d:'M0 -82 Q21 -56 22 -36 V54 H-22 V-36 Q-21 -56 0 -82Z',class:'capsule'}),E('path',{d:'M-22 35 L-35 64 -22 58 M22 35 35 64 22 58',fill:'#7694a7',opacity:'.6'}),E('path',{d:'M-22 -22H22 M-22 17H22',class:'rocket-seam'}),E('rect',{x:-21,y:18,width:42,height:35,fill:'#e4d9b9',opacity:'.55'}),E('rect',{x:-21,y:-35,width:42,height:12,fill:'#8da8c2',opacity:'.4'}),E('path',{d:'M-11 54 Q0 95 11 54',class:'flame'}),icon(model,22));g.append(E('text',{x:0,y:-40,'text-anchor':'middle',class:'rocket-label'},'ACT'),E('text',{x:0,y:40,'text-anchor':'middle',class:'rocket-label'},'MIND'));attach(g,model,'Three-stage rocket',rank,avg(model));layer.append(g);nodes.push({g,model,rank,score:avg(model),x})})}
if(reduced)chart.querySelectorAll('animate,animateTransform').forEach(a=>a.remove());select(selected);replay()}
function select(id){selected=id;for(const n of nodes)n.g.classList.toggle('is-muted',id!==null&&id!==n.model.id);document.querySelectorAll('.model-select button').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.model||null)===id)));tip.hidden=true}
function paint(t){for(const n of nodes){const progress=Math.max(0,Math.min(1,(t-n.rank*.017)/(1-n.rank*.017))),e=1-(1-progress)**3;let x,y;if(mode==='A'){const p=trackpoint(n.track,25+((n.displayScore??n.score)-25)*e);x=p.x;y=p.y}else if(mode==='B'){const center={mind:280,coupling:700,act:1120}[n.track];const row=Math.floor(n.rank/3),col=n.rank%3;const shift=row%2?20:-20;x=center+(col-1)*76+shift;const target=205+row*58;y=420+(target-420)*e;}else{x=n.x;const target=mode==='C'?430+(100-n.score)/75*590:320+(100-n.score)/75*590;y=1050+(target-1050)*e}n.finalPoint={x,y};n.g.setAttribute('transform',`translate(${x.toFixed(2)} ${y.toFixed(2)})`);n.g.style.opacity=String((mode==='B'&&n.track!=='coupling'?.9:1)*(.15+.85*Math.min(1,progress*4)))}}
function replay(){cancelAnimationFrame(frame);tip.hidden=true;if(reduced){paint(1);return}const start=performance.now();function tick(now){const t=Math.min(1,(now-start)/2600);paint(t);if(t<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}
for(const model of [{id:null,name:'All models'},...data.models]){const b=document.createElement('button');b.dataset.model=model.id||'';if(model.icon_svg){const s=new DOMParser().parseFromString(model.icon_svg,'image/svg+xml').documentElement;b.append(document.importNode(s,true))}b.append(document.createTextNode(model.name));b.addEventListener('click',()=>select(model.id));document.querySelector('.model-select').append(b)}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.mode)));document.querySelector('.lunar-replay').addEventListener('click',replay);render('B');window.Mind2ActLunar={replay,select,updateScores(models){if(!Array.isArray(models)||!models.length)throw new Error('Expected model score records');for(const m of models)for(const key of ['mind','act','coupling'])if(!Number.isFinite(m[key])||m[key]<0||m[key]>100)throw new Error('Scores must be between 0 and 100');const roster=new Map(data.models.map(m=>[m.id,m]));const next=models.map(m=>({...roster.get(m.id),...m}));if(next.some(m=>!m.icon_svg))throw new Error('Each model needs an icon');data.models=next;render('B');},getScores(){return data.models.map(({icon_svg,...m})=>({...m}));}};
})();

const mainLinks=[...document.querySelectorAll('#siteNav a[href^="#"]')];
function updateMainNavigation(){let active=mainLinks[0],nearest=-Infinity;for(const a of mainLinks){const section=document.querySelector(a.getAttribute('href'));const top=section?.getBoundingClientRect().top;if(top<=210&&top>nearest){nearest=top;active=a;}}mainLinks.forEach(a=>{if(a===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
window.addEventListener('scroll',updateMainNavigation,{passive:true});updateMainNavigation();
