(()=>{
const chart=document.querySelector('.moon-chart'),source=document.querySelector('#lunar-data');if(!chart||!source)return;
const ns='http://www.w3.org/2000/svg',data=JSON.parse(source.textContent),tracks=['mind','act','coupling'],reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const layer=chart.querySelector('#lunar-models'),marks=chart.querySelector('#lunar-marks'),tooltip=document.querySelector('.lunar-tooltip');let animation=0,started=false,selected=null;
function el(tag,attrs={},text){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!=null)n.textContent=text;return n;}
function point(track,score){const path=chart.querySelector('#flight-'+track),total=path.getTotalLength(),base=track==='coupling'?740:798,goal=base-(base-230)*score/100;let lo=0,hi=total;for(let i=0;i<22;i++){let mid=(lo+hi)/2;if(path.getPointAtLength(mid).y>goal)lo=mid;else hi=mid;}return path.getPointAtLength((lo+hi)/2);}
tracks.forEach(track=>{const x=track==='mind'?100:track==='act'?1300:770;const axis=el('g',{class:'orbit-tick '+track+'-tick'});[0,25,50,75,100].forEach(score=>{const p=point(track,score);axis.append(el('path',{d:`M${x-5} ${p.y}h10`}),el('text',{x:x+(track==='mind'?-16:16),y:p.y+5,'text-anchor':track==='mind'?'end':'start'},score));});marks.append(axis);});
const nodes=[];
tracks.forEach(track=>{const ranked=[...data.models].sort((a,b)=>b[track]-a[track]),occupied=[];
ranked.forEach((model,rank)=>{const score=model[track];if(!Number.isFinite(score)||score<0||score>100)return;const p=point(track,score);let offset=0;for(const candidate of [0,-40,40,-80,80,-120,120]){if(occupied.every(q=>(Math.abs(p.x+candidate-q.x)>45||Math.abs(p.y-q.y)>45))){offset=candidate;break;}}occupied.push({x:p.x+offset,y:p.y});
const g=el('g',{class:'live-craft '+track+'-craft','data-model':model.id,tabindex:'0',role:'button','aria-label':`${model.name}, ${track}, rank ${rank+1}, ${score} out of 100`});
const leader=el('path',{class:'marker-leader',d:`M0 0H${offset}`}),badge=el('g',{class:'model-badge',transform:`translate(${offset} 0)`});badge.append(el('circle',{r:22,class:'badge-halo'}),el('circle',{r:18,class:'badge-disc'}));
const icon=el('svg',{x:-10,y:-10,width:20,height:20,viewBox:'0 0 24 24',class:'brand-icon','aria-hidden':'true'});const parsed=new DOMParser().parseFromString(model.icon_svg,'image/svg+xml').documentElement;[...parsed.children].filter(n=>n.tagName!=='title').forEach(n=>icon.append(document.importNode(n,true)));badge.append(icon);g.append(leader,badge);layer.append(g);nodes.push({g,badge,track,model,score,rank,offset});
function show(){const title={mind:'Mind World',act:'Action World',coupling:'Mind2Act'}[track];tooltip.replaceChildren();const name=document.createElement('b');name.textContent=model.name;const line=document.createElement('span');line.textContent=`${title} · #${rank+1} · ${score}/100`;tooltip.append(name,line);tooltip.hidden=false;const rect=chart.getBoundingClientRect(),b=g.getBoundingClientRect();tooltip.style.left=Math.max(12,Math.min(rect.width-205,b.x-rect.x+b.width/2-92))+'px';tooltip.style.top=Math.max(12,b.y-rect.y-66)+'px';}
g.addEventListener('pointerenter',show);g.addEventListener('pointerleave',()=>tooltip.hidden=true);g.addEventListener('focus',show);g.addEventListener('blur',()=>tooltip.hidden=true);g.addEventListener('click',()=>{select(model.id);show();});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(model.id);show();}});
});});
const controls=document.querySelector('.model-select');[{id:null,name:'All models'},...data.models].forEach(model=>{const b=document.createElement('button');b.type='button';b.dataset.model=model.id||'';if(model.icon_svg){const svg=new DOMParser().parseFromString(model.icon_svg,'image/svg+xml').documentElement;svg.setAttribute('aria-hidden','true');b.append(document.importNode(svg,true));}const label=document.createElement('span');label.textContent=model.name;b.append(label);b.addEventListener('click',()=>select(model.id));controls.append(b);});
function select(id){selected=id;nodes.forEach(n=>{n.g.classList.toggle('is-muted',id!==null&&id!==n.model.id);n.g.classList.toggle('is-selected',id===n.model.id);});controls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.model||null)===id)));tooltip.hidden=true;}
function paint(progress){nodes.forEach(n=>{const delay=n.rank*.025,t=Math.max(0,Math.min(1,(progress-delay)/(1-delay))),e=1-Math.pow(1-t,3),p=point(n.track,n.score*e);n.g.setAttribute('transform',`translate(${p.x.toFixed(2)} ${p.y.toFixed(2)})`);n.g.style.opacity=String(.08+.92*Math.min(1,t*5));});}
function replay(){cancelAnimationFrame(animation);tooltip.hidden=true;if(reduced){paint(1);return;}const start=performance.now();function frame(now){const t=Math.min(1,(now-start)/2800);paint(t);if(t<1)animation=requestAnimationFrame(frame);}animation=requestAnimationFrame(frame);}
document.querySelector('.lunar-replay').addEventListener('click',replay);select(null);paint(reduced?1:0);if('IntersectionObserver'in window)new IntersectionObserver((entries,o)=>{if(entries.some(e=>e.isIntersecting)&&!started){started=true;replay();o.disconnect();}},{threshold:.15}).observe(chart);else replay();window.Mind2ActLunar={replay,select};
})();
