import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const base='.production/insets-20261010-200358';
const d=JSON.parse(fs.readFileSync(`${base}/delivery-candidate.json`,'utf8'));
const previous=JSON.parse(fs.readFileSync(`${base}/before/renders/delivery.json`,'utf8'));
if(!JSON.parse(fs.readFileSync(`${base}/check-final.json`,'utf8')).ok)throw Error('Composition gate failed');
if(!JSON.parse(fs.readFileSync(`${base}/audio-continuity.json`,'utf8')).bit_identical)throw Error('Audio identity changed: run full AAC audit before release');
if(createHash('sha256').update(fs.readFileSync(previous.master)).digest('hex')!==previous.files.master.sha256)throw Error('Historical master changed');
const stamp=d.id.replace('mind2act-world-promo-','');
d.local_preview=`renders/preview-${stamp}.html`;
const oldHtml=fs.readFileSync(previous.local_preview,'utf8');
fs.writeFileSync(d.local_preview,oldHtml.replaceAll(previous.id.replace('mind2act-world-promo-',''),stamp));
d.checks.audio_continuity=`${base}/audio-continuity.json`;
d.checks.aac=previous.checks.aac;
d.checks.review=`${base}/QA.md`;
d.checks.exported_frames=`${base}/rendered`;
d.source_hashes={};
for(const file of ['index.html',...fs.readdirSync('compositions').filter(n=>n.endsWith('.html')).map(n=>`compositions/${n}`)])d.source_hashes[file]=createHash('sha256').update(fs.readFileSync(file)).digest('hex');
d.verified_at=new Date().toISOString();
const json=JSON.stringify(d,null,2)+'\n';
fs.writeFileSync(`renders/delivery-${stamp}.json`,json);
fs.writeFileSync('renders/delivery.json',json);
fs.writeFileSync(`${base}/delivery-final.json`,json);
let readme=fs.readFileSync('renders/README.md','utf8');
readme=readme.replaceAll(previous.id.replace('mind2act-world-promo-',''),stamp).replace('72.0 MB',`${(d.files.master.bytes/1e6).toFixed(1)} MB`).replace('10.5 MB',`${(d.files.web.bytes/1e6).toFixed(1)} MB`);
fs.writeFileSync('renders/README.md',readme);
console.log(JSON.stringify({id:d.id,master:d.master,web:d.web,preview:d.local_preview,duration:d.files.master.duration}));
